// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.28.2
// source: protobuf/events.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_UNKNOWN Action = 0
	Action_FIGHT   Action = 1
	Action_CRAFT   Action = 2
	Action_GATHER  Action = 3
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "UNKNOWN",
		1: "FIGHT",
		2: "CRAFT",
		3: "GATHER",
	}
	Action_value = map[string]int32{
		"UNKNOWN": 0,
		"FIGHT":   1,
		"CRAFT":   2,
		"GATHER":  3,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_protobuf_events_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_protobuf_events_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_protobuf_events_proto_rawDescGZIP(), []int{0}
}

type UserEvent struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Action Action `protobuf:"varint,2,opt,name=action,proto3,enum=idlerpg.Action" json:"action,omitempty"`
	Exp    int32  `protobuf:"varint,3,opt,name=exp,proto3" json:"exp,omitempty"`
}

func (x *UserEvent) Reset() {
	*x = UserEvent{}
	mi := &file_protobuf_events_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserEvent) ProtoMessage() {}

func (x *UserEvent) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_events_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserEvent.ProtoReflect.Descriptor instead.
func (*UserEvent) Descriptor() ([]byte, []int) {
	return file_protobuf_events_proto_rawDescGZIP(), []int{0}
}

func (x *UserEvent) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserEvent) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_UNKNOWN
}

func (x *UserEvent) GetExp() int32 {
	if x != nil {
		return x.Exp
	}
	return 0
}

type UserUpdate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int32 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *UserUpdate) Reset() {
	*x = UserUpdate{}
	mi := &file_protobuf_events_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserUpdate) ProtoMessage() {}

func (x *UserUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_events_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserUpdate.ProtoReflect.Descriptor instead.
func (*UserUpdate) Descriptor() ([]byte, []int) {
	return file_protobuf_events_proto_rawDescGZIP(), []int{1}
}

func (x *UserUpdate) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

var File_protobuf_events_proto protoreflect.FileDescriptor

var file_protobuf_events_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x76, 0x65, 0x6e, 0x74,
	0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x69, 0x64, 0x6c, 0x65, 0x72, 0x70, 0x67,
	0x22, 0x56, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x45, 0x76, 0x65, 0x6e, 0x74, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x27, 0x0a,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f, 0x2e,
	0x69, 0x64, 0x6c, 0x65, 0x72, 0x70, 0x67, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06,
	0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x78, 0x70, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x65, 0x78, 0x70, 0x22, 0x1c, 0x0a, 0x0a, 0x55, 0x73, 0x65, 0x72,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x2a, 0x37, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x12, 0x0b, 0x0a, 0x07, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x46, 0x49, 0x47, 0x48, 0x54, 0x10, 0x01, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x52, 0x41, 0x46,
	0x54, 0x10, 0x02, 0x12, 0x0a, 0x0a, 0x06, 0x47, 0x41, 0x54, 0x48, 0x45, 0x52, 0x10, 0x03, 0x42,
	0x0b, 0x5a, 0x09, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_events_proto_rawDescOnce sync.Once
	file_protobuf_events_proto_rawDescData = file_protobuf_events_proto_rawDesc
)

func file_protobuf_events_proto_rawDescGZIP() []byte {
	file_protobuf_events_proto_rawDescOnce.Do(func() {
		file_protobuf_events_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_events_proto_rawDescData)
	})
	return file_protobuf_events_proto_rawDescData
}

var file_protobuf_events_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protobuf_events_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_protobuf_events_proto_goTypes = []any{
	(Action)(0),        // 0: idlerpg.Action
	(*UserEvent)(nil),  // 1: idlerpg.UserEvent
	(*UserUpdate)(nil), // 2: idlerpg.UserUpdate
}
var file_protobuf_events_proto_depIdxs = []int32{
	0, // 0: idlerpg.UserEvent.action:type_name -> idlerpg.Action
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_events_proto_init() }
func file_protobuf_events_proto_init() {
	if File_protobuf_events_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_events_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protobuf_events_proto_goTypes,
		DependencyIndexes: file_protobuf_events_proto_depIdxs,
		EnumInfos:         file_protobuf_events_proto_enumTypes,
		MessageInfos:      file_protobuf_events_proto_msgTypes,
	}.Build()
	File_protobuf_events_proto = out.File
	file_protobuf_events_proto_rawDesc = nil
	file_protobuf_events_proto_goTypes = nil
	file_protobuf_events_proto_depIdxs = nil
}
