apiVersion: apps/v1
kind: Deployment
metadata:
  name: idlerpg-deploy
  namespace: idlerpg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: idlerpg
  template:
    metadata:
      labels:
        app: idlerpg
    spec:
      containers:
        - image: idlerpg:latest
          imagePullPolicy: Always
          name: idlerpg
          envFrom:
            - configMapRef:
                name: idlerpg-cm
          ports:
            - containerPort: 3000
          resources:
            requests:
              cpu: 1000m
              memory: 2Gi
            limits:
              cpu: 2000m
              memory: 3Gi
