apiVersion: v1
kind: Service
metadata:
  name: controller-1-svc
  labels:
    service: controller-1
spec:
  ports:
    - port: 9093
      targetPort: 9093
  selector:
    service: controller-1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: controller-1
  name: controller-1
spec:
  serviceName: controller-1
  replicas: 1
  selector:
    matchLabels:
      service: controller-1
  template:
    metadata:
      labels:
        network/kafka-network: "true"
        service: controller-1
    spec:
      securityContext:
        fsGroup: 1000
      enableServiceLinks: false
      restartPolicy: Always
      containers:
        - image: apache/kafka:latest
          imagePullPolicy: Always
          name: controller-1
          env:
            - name: KAFKA_NODE_ID
              value: 1
            - name: KAFKA_PROCESS_ROLES
              value: controller
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_LISTENERS
              value: "CONTROLLER://:9093"
            - name: CLUSTER_ID
              value: "4L6g3nShT-eMCtK--X86sw"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: 3
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: 0
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: 2
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: 3
            - name: KAFKA_LOG_DIRS
              value: "/tmp/kraft-combined-logs"
          resources: {}
          # volumeMounts:
          #   - mountPath: /var/lib/zookeeper/data
          #     name: zookeeper-data
          #   - mountPath: /var/lib/zookeeper/log
          #     name: zookeeper-log
  # volumeClaimTemplates:
  #   - metadata:
  #       name: zookeeper-data
  #     spec:
  #       accessModes:
  #         - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 1024Mi
  #   - metadata:
  #       name: zookeeper-log
  #     spec:
  #       accessModes:
  #         - ReadWriteOnce
  #       resources:
  #         requests:
  #           storage: 1024Mi
