apiVersion: v1
kind: Service
metadata:
  name: kafka-2-serv
  labels:
    service: kafka-2
spec:
  clusterIP: None
  selector:
    service: kafka-2
  ports:
    - name: internal
      port: 19092
      targetPort: 19092
    - name: external
      port: 39092
      targetPort: 9092
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    service: kafka-2
  name: kafka-2
spec:
  serviceName: kafka-2
  replicas: 1
  selector:
    matchLabels:
      service: kafka-2
  template:
    metadata:
      labels:
        network/kafka-network: "true"
        service: kafka-2
    spec:
      securityContext:
        fsGroup: 1000
      enableServiceLinks: false
      containers:
        - image: apache/kafka:latest
          name: kafka-2
          imagePullPolicy: IfNotPresent
          hostname: kafka-2
          restartPolicy: Always
          ports:
            - containerPort: 39092
            - containerPort: 9092
          env:
            - name: KAFKA_NODE_ID
              value: 5
            - name: KAFKA_PROCESS_ROLES
              value: broker
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:19092,PLAINTEXT_HOST://:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: CLUSTER_ID
              value: "4L6g3nShT-eMCtK--X86sw"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: 3
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: 0
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: 2
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: 3
            - name: KAFKA_LOG_DIRS
              value: "/tmp/kraft-combined-logs"
          resources: {}
