apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
  namespace: kafka
  labels:
    app: kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - image: apache/kafka:latest
          name: controller-1
          env:
            - name: KAFKA_NODE_ID
              value: 1
            - name: KAFKA_PROCESS_ROLES
              value: controller
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_LISTENERS
              value: "CONTROLLER://:9093"
            - name: CLUSTER_ID
              value: "4L6g3nShT-eMCtK--X86sw"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: 3
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: 0
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: 2
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: 3
            - name: KAFKA_LOG_DIRS
              value: "/tmp/kraft-combined-logs"
          resources:
            limits:
              memory: 50Mi
              cpu: 25m
        - image: apache/kafka:latest
          name: controller-2
          env:
            - name: KAFKA_NODE_ID
              value: 2
            - name: KAFKA_PROCESS_ROLES
              value: controller
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_LISTENERS
              value: "CONTROLLER://:9093"
            - name: CLUSTER_ID
              value: "4L6g3nShT-eMCtK--X86sw"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: 3
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: 0
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: 2
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: 3
            - name: KAFKA_LOG_DIRS
              value: "/tmp/kraft-combined-logs"
          resources:
            limits:
              memory: 50Mi
              cpu: 25m
        - image: apache/kafka:latest
          name: controller-3
          env:
            - name: KAFKA_NODE_ID
              value: 3
            - name: KAFKA_PROCESS_ROLES
              value: controller
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: KAFKA_LISTENERS
              value: "CONTROLLER://:9093"
            - name: CLUSTER_ID
              value: "4L6g3nShT-eMCtK--X86sw"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: 3
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: 0
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: 2
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: 3
            - name: KAFKA_LOG_DIRS
              value: "/tmp/kraft-combined-logs"
          resources:
            limits:
              memory: 50Mi
              cpu: 25m
        - image: apache/kafka:latest
          name: kafka-1
          port:
            - port: 29092
              containerPort: 9092
          env:
            - name: KAFKA_NODE_ID
              value: 4
            - name: KAFKA_PROCESS_ROLES
              value: broker
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:19092,PLAINTEXT_HOST://:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: CLUSTER_ID
              value: "4L6g3nShT-eMCtK--X86sw"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: 3
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: 0
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: 2
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: 3
            - name: KAFKA_LOG_DIRS
              value: "/tmp/kraft-combined-logs"
          resources:
            limits:
              memory: 50Mi
              cpu: 25m
        - image: apache/kafka:latest
          name: kafka-2
          port:
            - port: 39092
              containerPort: 9092
          env:
            - name: KAFKA_NODE_ID
              value: 5
            - name: KAFKA_PROCESS_ROLES
              value: broker
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:19092,PLAINTEXT_HOST://:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: CLUSTER_ID
              value: "4L6g3nShT-eMCtK--X86sw"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: 3
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: 0
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: 2
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: 3
            - name: KAFKA_LOG_DIRS
              value: "/tmp/kraft-combined-logs"
          resources:
            limits:
              memory: 50Mi
              cpu: 25m
        - image: apache/kafka:latest
          name: kafka-3
          port:
            - port: 49092
              containerPort: 9092
          env:
            - name: KAFKA_NODE_ID
              value: 6
            - name: KAFKA_PROCESS_ROLES
              value: broker
            - name: KAFKA_CONTROLLER_QUORUM_VOTERS
              value: 1@controller-1:9093,2@controller-2:9093,3@controller-3:9093
            - name: KAFKA_LISTENERS
              value: "PLAINTEXT://:19092,PLAINTEXT_HOST://:9092"
            - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
              value: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            - name: KAFKA_INTER_BROKER_LISTENER_NAME
              value: PLAINTEXT
            - name: KAFKA_CONTROLLER_LISTENER_NAMES
              value: CONTROLLER
            - name: CLUSTER_ID
              value: "4L6g3nShT-eMCtK--X86sw"
            - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
              value: 3
            - name: KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS
              value: 0
            - name: KAFKA_TRANSACTION_STATE_LOG_MIN_ISR
              value: 2
            - name: KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR
              value: 3
            - name: KAFKA_LOG_DIRS
              value: "/tmp/kraft-combined-logs"
          resources:
            limits:
              memory: 50Mi
              cpu: 25m
