package postgresqlcnpgio


// Affinity/Anti-affinity rules for Pods.
type ClusterSpecAffinity struct {
	// AdditionalPodAffinity allows to specify pod affinity terms to be passed to all the cluster's pods.
	AdditionalPodAffinity *ClusterSpecAffinityAdditionalPodAffinity `field:"optional" json:"additionalPodAffinity" yaml:"additionalPodAffinity"`
	// AdditionalPodAntiAffinity allows to specify pod anti-affinity terms to be added to the ones generated by the operator if EnablePodAntiAffinity is set to true (default) or to be used exclusively if set to false.
	AdditionalPodAntiAffinity *ClusterSpecAffinityAdditionalPodAntiAffinity `field:"optional" json:"additionalPodAntiAffinity" yaml:"additionalPodAntiAffinity"`
	// Activates anti-affinity for the pods.
	//
	// The operator will define pods
	// anti-affinity unless this field is explicitly set to false.
	EnablePodAntiAffinity *bool `field:"optional" json:"enablePodAntiAffinity" yaml:"enablePodAntiAffinity"`
	// NodeAffinity describes node affinity scheduling rules for the pod.
	//
	// More info: https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#node-affinity
	NodeAffinity *ClusterSpecAffinityNodeAffinity `field:"optional" json:"nodeAffinity" yaml:"nodeAffinity"`
	// NodeSelector is map of key-value pairs used to define the nodes on which the pods can run.
	//
	// More info: https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
	NodeSelector *map[string]*string `field:"optional" json:"nodeSelector" yaml:"nodeSelector"`
	// PodAntiAffinityType allows the user to decide whether pod anti-affinity between cluster instance has to be considered a strong requirement during scheduling or not.
	//
	// Allowed values are: "preferred" (default if empty) or
	// "required". Setting it to "required", could lead to instances remaining pending until new kubernetes nodes are
	// added if all the existing nodes don't match the required pod anti-affinity rule.
	// More info:
	// https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/#inter-pod-affinity-and-anti-affinity
	PodAntiAffinityType *string `field:"optional" json:"podAntiAffinityType" yaml:"podAntiAffinityType"`
	// Tolerations is a list of Tolerations that should be set for all the pods, in order to allow them to run on tainted nodes.
	//
	// More info: https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/
	Tolerations *[]*ClusterSpecAffinityTolerations `field:"optional" json:"tolerations" yaml:"tolerations"`
	// TopologyKey to use for anti-affinity configuration.
	//
	// See k8s documentation
	// for more info on that.
	TopologyKey *string `field:"optional" json:"topologyKey" yaml:"topologyKey"`
}

